### ISSUE TITLE
thread 'main' panicked at 'attempt to subtract with overflow' when pressing right key

### ISSUE THREAD

**Issue by Badel2** [Canop/safecloset#1]
It's hard to explain where this happens, so I uploaded an example to asciinema:

https://asciinema.org/a/ZdnzccVnoGFmfA2QmklmKm3hX

Basically after writing "aaa" I press "enter" and then "right arrow", and the program panics.

You can't see the backtrace when running this command, however thanks to the magic of asciinema I was able to recover it:

> "thread 'main' panicked at 'attempt to subtract with overflow', src/tui/drawer_edit_state.rs:159:21\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n"

Which points to this line:

https://github.com/Canop/safecloset/blob/232b7f22abfebfc379b62f83b6dc2c85ccde5679/src/tui/drawer_edit_state.rs#L159

If the desired behavior is wrapping on overflow (same as when compiling with `--release`), try using `.wrapping_sub(1)` instead of `- 1`.

**Comment by Canop** [comment]
Thanks for the very precise bug report
