### ISSUE TITLE
Could you add command line version of the program?

### ISSUE THREAD

**Issue by FikretSanda** [Canop/safecloset#11]
Thanks for creating safecloset. It's a very useful utility! 

Current SC use TUI for everything. If there is a command line interface so that users can add, query, delete, change drawer entries, that would make the program more versatile and can be used under more situations.

**Comment by Canop** [comment]
I'll probably add some commands, like merging or splitting closets.

But I don't want to have much done outside of the secured TUI. Most importantly, I won't allow passing a password as argument. SafeCloset was designed to avoid the security flaws of the shell.

**Comment by FikretSanda** [comment]
If password as argument is not an option, is there a way to automate safecloset in CI/CD process? I have multiple pieces of password protected info in safecloset and I hope I can use grab them in the CI/CD process.

**Comment by Canop** [comment]
What would be your workflow ? How would you give the drawer's password to your CI ?
