### ISSUE TITLE
Paste multiline text doesn't work

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [Canop/safecloset#12]
I'm on Windows and using v0.4.0. It seems that I can't paste multiline text in the info entry UI. When I do that, they get concatenated and some characters were missing. Also it seems that I can't add newline in the left cells. Is this expected? See below image for details.
![safe1](https://user-images.githubusercontent.com/39968/142170544-775e566b-2637-4807-9987-ba4a1ff32e23.gif)

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Btw, the upper image is from Windows Terminal. I also tried cmd.exe and it behaved the same.

**Comment by Canop** [comment]
* Missing newline on pasting in values doesn't happen on other platforms. I think I know what happens. I'll fix that (I might ask you to check a branch as I've no Windows computer at home)
* left cells are the names of entries while right cells are the values. It's by design that names are short (normally not secret) and can't contain newlines

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Thanks for the response. I'm happy to test.

**Comment by Canop** [comment]
Could you please test where I develop the text editing component, that is in [the Termimad crate](https://github.com/Canop/termimad) and in this repository try the relevant example with `cargo run --example inputs` ?

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
> Could you please test where I develop the text editing component, that is in [the Termimad crate](https://github.com/Canop/termimad) and in this repository try the relevant example with `cargo run --example inputs` ?

The example works well.
![termimad_example](https://user-images.githubusercontent.com/39968/142384634-4db9b592-c950-43a5-868d-ac97a835fe2c.gif)

**Comment by Canop** [comment]
So it should work in the version of SafeCloset I released a few hours ago (0.5.1). Can you confirm that?

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
> So it should work in the version of SafeCloset I released a few hours ago (0.5.1). Can you confirm that?

I tried, same behavior.
![issue2](https://user-images.githubusercontent.com/39968/142386100-7f255bf5-4787-49cb-8a06-ab1293f38119.gif)

**Comment by Canop** [comment]
I must be missing something obvious...

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Ok, let me try.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
It looks like this:
![issue3](https://user-images.githubusercontent.com/39968/142389160-19323045-fc6e-426b-86a7-cf74ec3c9a96.gif)

**Comment by Canop** [comment]
Thanks for the detailed test report.

**Comment by Hetasser** [comment]
Hi
just tested version 0.5.1 and multiline worked on cmd and powershell
I'm using Windows 11

only one line is displayed until I click on it, then it shows every line
![image](https://user-images.githubusercontent.com/1140345/142496041-3bfef3fd-e3e0-40bd-bd88-ea609b8716ba.png)
![image](https://user-images.githubusercontent.com/1140345/142496056-d08372b5-353b-4665-bb07-eb81a908c60a.png)

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
I tested again on a clean Win10 VM and it behaved the same. Maybe it only happens on Win10? Not sure.

**Comment by Canop** [comment]
Managed to launch Windows in VirtualBox
There are **a lot** of things to fix in the Windows version of SafeCloset Oo
but I don't observe any problem with pasting
![image](https://user-images.githubusercontent.com/617006/142604036-d50694cd-6708-4a21-9e2b-350171de5307.png)

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
> Managed to launch Windows in VirtualBox There are **a lot** of things to fix in the Windows version of SafeCloset Oo but I don't observe any problem with pasting ![image](https://user-images.githubusercontent.com/617006/142604036-d50694cd-6708-4a21-9e2b-350171de5307.png)

Congrats for the Windows environment!
Based on you guy's feedback, I did some more testing and I think I've found the problem. I said `I also tried cmd.exe and it behaved the same` before, it's because I always use the system menu of the cmd window during the testing (see below image). I just found that if I use <kbd>ctrl</kbd><kbd>v</kbd> directly, multiline text pasting magically works! This is the exactly same behavior of the native PowerShell console (the one you are using in VirtualBox).
![issue4](https://user-images.githubusercontent.com/39968/142628052-9a7e514b-4a1f-43b2-b353-7e01fcd01370.gif)
 
For [Windows Terminal](https://github.com/microsoft/terminal), it's another issue. Newer version of Windows Terminal set <kbd>ctrl</kbd><kbd>v</kbd> as pasting by default. It has `{ "command": "paste", "keys": "ctrl+v" },` in its configuration file. So the handling of <kbd>ctrl</kbd><kbd>v</kbd> in safecloset got interfered. I changed it to `{ "command": "paste", "keys": "ctrl+shift+v" },`, and again, multiline text pasting works now!

So all in all, it's not safecloset's problem.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
> There are **a lot** of things to fix in the Windows version of SafeCloset Oo

Are there any big issues you have found?

**Comment by Canop** [comment]
I've reproduced (and fixed) the duplicate status line. There are problems of speed, sometimes a visible cursor at the bottom, things like that. Nothing impacting the security if that's what you had in mind.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Can we add this issue to the document so that others may find it useful? Since Windows Terminal is getting popular on Windows, Windows safecloset users may meet the safe pasting issue.

**Comment by Canop** [comment]
Just have to find where to insert a FAQ in [the site)(https://dystroy.org/safecloset/)

**Comment by Canop** [comment]
@0x7FFFFFFFFFFFFFFF You'd be the most qualified to write this precise FAQ entry. Can you make a PR (with a random location, I'll add the page afterwards) ?

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
> @0x7FFFFFFFFFFFFFFF You'd be the most qualified to write this precise FAQ entry. Can you make a PR (with a random location, I'll add the page afterwards) ?

OK I'll do it. But remember to proofread as there may be grammar issues 😅  (I'm not a native English speaker).

**Comment by Canop** [comment]
> there may be grammar issues
Don't worry, they won't feel alone...
