### ISSUE TITLE
Support Termux

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [Canop/safecloset#13]
Since safecloset is very useable now, I migrated my secret management fully to it. I hope I can run it on my Android devices. I tried build it under Termux, but I got this error:
![Screenshot_20211117-185636_Termux](https://user-images.githubusercontent.com/39968/142189295-43c6dfdf-afac-46eb-8d8d-3f0296ff9e75.png)

Do you know how to solve it? Since it's from a color related crate, is it possible to remove color support if not easy to solve. Thanks.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
I also tried to install the suggested package, but Termux told me it can't be found.

**Comment by Canop** [comment]
It doesn't right now but I can make it so, as I've already made some other TUI compatible with it. It's just a matter of finding the time to work on it.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Glad to hear that!

**Comment by Canop** [comment]
For some reason the installation of Termux fails on my smartphone with Android 12...

The release archive that can be downloaded on GitHub (https://github.com/Canop/safecloset/releases/tag/v0.4.0) contains a Termux application (untested). Could you try it ?
If you don't want to trust a precompiled binary downloaded from GitHub, you can do as I do, which is to compile on linux with the compile-all-targets.sh script which is in this repository.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
From the document of Termux, it seems Android 12 is not supported yet. 
> Will Termux work on Android 11
> In short: yes, it works on Android 11 and even 12 beta.
 
I don't know the release contains executables. It's great! Your work is definitely trusted for sure! I'll use the Windows version directly in the future. For learning purpose, I built manually this time (I'm learning Rust too). After I installed cross, the build script works well. Copy the output binary to Android, chmod +x, and it runs well and looks exactly like it does on other systems. Cool!

However, I did find an issue. The copy to clipboard feature doesn't work well. If I remember it correctly, it worked only for the first time. When I wanted to confirm, it never worked again, this happened even I restarted safecloset. I did a Google search and it seems copy to clipboard in Termux is a tricky issue. Anyway, I'll do more testing later.

**Comment by Canop** [comment]
Copying on termux should work but only if you've installed the additional "Termux API" (it can be done from inside Termux).

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Yes! The copy feature works well after installed the plugin. I tested and found the only feature that doesn't work is the Ctrl+a to expand all. All other features work as expected.

**Comment by Canop** [comment]
Hum. I realize I didn't upgrade the documentations when I changed the shortcut from Ctrl-A to Ctrl-F...

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Great! Now everything works! Thank you so much for the guidance!
