### ISSUE TITLE
Can't use mouse select cell content

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [Canop/safecloset#17]
I'm on Windows and use SafeCloset 0.5.2. When I use mouse to select the cell content, SafeCloset exits with an error message `Error: Crossbeam(RecvError)`. Is SafeCloset designed so that the user is not allowed to select text inside the program with the mouse? I'm using Windows Terminal and by default Windows Terminal will copy the selection to clipboard. And that's why I was making the selection. 
![selection_error](https://user-images.githubusercontent.com/39968/143542129-4383c852-1df0-4902-b975-dce93329cd31.gif)

**Comment by Canop** [comment]
> Is SafeCloset designed so that the user is not allowed to select text inside the program with the mouse?

No, this is a bug, I'll look into it.

**Comment by Canop** [comment]
I can reproduce the crash in a Windows emulator

**Comment by Canop** [comment]
This is a bug in Crossterm (see link above).
![image](https://user-images.githubusercontent.com/617006/143614421-e74213e8-5002-4082-81b8-4b56273295fc.png)

**Comment by Canop** [comment]
It looks like the new version of Crossterm should at least prevent the panic. I'll try upgrading (some changes are needed in my code).

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Thank you!
