### ISSUE TITLE
When the cell contains non-ASCII characters, selection doesn't work correctly

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [Canop/safecloset#18]
Environment:
- OS: Windows 10
- Terminal: Windows Terminal 1.11.2921.0
- SafeCloset: SafeCloset 0.5.3-dev

I found that when the cell contains non-ASCII chars, I can't correctly make selection. But even the cell contains non-ASCII chars, lines that don't contain non-ASCII chars can still be selected correctly. 

![selection_issue](https://user-images.githubusercontent.com/39968/143669625-f44cb1a5-bcef-4a0e-8227-e2c9d7af3c8b.gif)

You can try this text:
```
そのスレッドがまだ実行されている間While that thread was still executing
While that thread was still executing
While that thread was still executing
```

**Comment by Canop** [comment]
OK. The problem is that the mouse position is badly converted into characters count when some characters take more (or less, I suppose) than one cell.

I'll fix that.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Thanks for the hard work.
