### ISSUE TITLE
Newline doesn't work on Windows

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [Canop/safecloset#2]
In the document it states that

> You may add newlines in values with ctrl enter

and 

> alt-Enter : New line in the currently edited value

However, I tried both on Windows and it doesn't work. I tried both Windows Terminal and the old school cmd.exe, same result.

**Comment by Canop** [comment]
We need to find a combination which works on Windows. I'll probably have to make a dedicated program for that.

**Comment by Canop** [comment]
Are you building from source ? If so can you add this line
```rust
                debug!("user event: {:?}", &event);
```
line 36 of src/tui/app.rs
then launch 

`SAFECLOSET_LOG=debug cargo run -- file.closet`

so that all key you try are logged in safecloset.log, which would let us know which key combinations may be used on your terminal

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
> ```rust
> debug!("user event: {:?}", &event);
> ```

I'll try it and update.

**Comment by Canop** [comment]
I've this line in most of my programs... but having a keylogger in safecloset didn't look like a brilliant idea ^^

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
> I've this line in most of my programs... but having a keylogger in safecloset didn't look like a brilliant idea ^^

lol, I haven't thought of a keylogger.

I tried it and below is the result (partially).
```
00:00:24.828 [DEBUG] safecloset::tui::app: user event: Ok(Key(KeyEvent { code: Char('a'), modifiers: NONE }))
00:00:31.992 [DEBUG] safecloset::tui::app: user event: Ok(Key(KeyEvent { code: Enter, modifiers: CONTROL }))
00:00:32.742 [DEBUG] safecloset::tui::app: user event: Ok(Key(KeyEvent { code: Enter, modifiers: CONTROL }))
00:00:33.359 [DEBUG] safecloset::tui::app: user event: Ok(Key(KeyEvent { code: Enter, modifiers: CONTROL }))
```
The first entry is my trying to edit a cell. Then I tried <kbd>ctrl+Enter</kbd> three times. But no newline was added. I also tried <kbd>alt+Enter</kbd>, but on newer version of Windows, this shortcut seems was intercepted by Windows to make the terminal full screen (both Windows Terminal and cmd.exe).

**Comment by Canop** [comment]
It means that ctrl-enter goes till safecloset. It's not currently bound.
I'll change safecloset to accept both alt-enter and ctrl-enter as a newline in values, I guess.

**Comment by Canop** [comment]
I've pushed a new branch, called `newline`. Could you test it ?

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Thank you! For the newline branch, both ctrl+enter and alt+enter works for both Windows Terminal. I also learned that I can disable the alt+enter for Windows Terminal. After that alt+enter works for both the master and newline branch. For cmd.exe, only ctrl+enter works in the newline branch.
