### ISSUE TITLE
Bottom bar shortcuts are changing while typing

### ISSUE THREAD

**Issue by angel-git** [Canop/safecloset#20]
Using mac on latest `main` branch:

https://user-images.githubusercontent.com/1565058/145171131-82056cb6-6711-4ff4-9247-8521a7d9fb3c.mp4

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Lol, this is interesting. Not a big issue, and it could be a feature. But let's wait for the author to explain a little bit.

**Comment by Canop** [comment]
If your concern is the changing hint at the bottom, then it's a "feature".

I mean the bottom bar is supposed to give hints, and not always the same ones.

I didn't really notice the distraction it can be when you're editing a long field.

Do you think it's more of a nuisance ?

**Comment by angel-git** [comment]
The issue is that when you are in "edit mode" sometimes it says `/ to search` but if you type `/` it's gonna type it on screen instead of searching so the hints might be confusing depending on the context where you are, on the other hand i guess it's only an issue the first time when you don't know the shortcuts :)

**Comment by Canop** [comment]
Oh, didn't notice that point. The hint is definitely not right in this context, I'll fix it.
