### ISSUE TITLE
Feature request: copy the content of the current cell with a shortcut

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [Canop/safecloset#3]
Once the user find the secret information, he/she may need to copy it and paste to some other places. If you add a shortcut to make the copy process a little bit easier it will make the app more usable. I suggest change the following

> ctrl c : Close the current drawer, without saving (you're back in the upper level one if you close a deep drawer)

to <kbd>ctrl+u</kbd>, which means go to *u*pper level. And make <kbd>ctrl+c</kbd>to copy current cell value, <kbd>ctrl+shift+c</kbd> to copy both name and value (separated by a newline). 

This is just an idea I had. Thanks for creating such a useful tool!

**Comment by Canop** [comment]
The `ctrl+u` idea also solves another problem: the risk of having users accidentally close their drawer when trying to copy.

**Comment by Canop** [comment]
I've pushed an implementation of the ctrl-c but I've trouble making it work on X11 so I won't publicize it immediately

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
I'm on Windows 10. The copy feature works well! Thanks for the implementation.
