### ISSUE TITLE
Feature Request: Allow sorting (probably alphabetically) through a drawer and/or potentially a search result

### ISSUE THREAD

**Issue by paletochen** [Canop/safecloset#31]
**Example 1 - Full drawer**

I have a drawer with login passwords dumped from Google Chrome, which was originally sorted from the export.
I keep updating that list of logins manually now in safecloset.

I'd like to have all those logins sorted so i can easily scroll through them, if that is my desire.

**Example 2 - Sort over a search result**
I keep a drawer for several types of secrets.
After a while some entries are misplaced or spread around the drawer, though they are in a way possible to sort, through a numbering system that i used, or alphabetically.

It would be great to use the search feature, find the secrets and be able to sort them.
Alphabetical order could be a good automatic start.

The doubt in Example 2 would be how the result would look like when the secrets to sort are not contiguous within the drawer.

Let's take this following case to clarify this doubt:

- [login] abc - xxx
- [login] abd -xxx
- **[pin] door 1 - xxx**
- **[pin] door 2 - xxx**
- [login] cfg -xxx
- **[pin] door 5 - xxx**
- **[pin] door 4 -xxx**
- [login] cfgds -xxx
- **[pin] door 3 - xxx**

If i filter for [pin] and click sort, how would the drawer look like?

Like this?
- [login] abc - xxx
- [login] abd -xxx
- **[pin] door 1 - xxx**
- **[pin] door 2 - xxx**
- [login] cfg -xxx
- **[pin] door 3 - xxx**
- **[pin] door 4 -xxx**
- [login] cfgds -xxx
- **[pin] door 5 - xxx**

Like this?
- [login] abc - xxx
- [login] abd -xxx
- **[pin] door 1 - xxx**
- **[pin] door 2 - xxx**
- **[pin] door 3 - xxx**
- **[pin] door 4 -xxx**
- **[pin] door 5 - xxx**
- [login] cfg -xxx
- [login] cfgds -xxx

In another way?

**Comment by Canop** [comment]
On second thought, I don't think I'll allow sorting when a filter is applied. I'm sure most people would expect a result different than any specification I would define. And it's unlikely to be useful anyway.

**Comment by Canop** [comment]
@paletochen Can you check the PR #33 and tell me whether it looks OK to you ?

**Comment by Canop** [comment]
Also relevant: https://github.com/Canop/safecloset/pull/35

**Comment by paletochen** [comment]
> @paletochen Can you check the PR #33 and tell me whether it looks OK to you ?

Sorting for the full drawer works perfectly

**Comment by Canop** [comment]
@paletochen New version also sorts when the list is filtered

**Comment by paletochen** [comment]
> @paletochen New version also sorts when the list is filtered

Amazing! 
Works perfectly. 
The combo of grouping and sorting is extremely powerful. It allows me to make changes in batch to very big drawers.

Thank you very much!
