### ISSUE TITLE
Feature request: Allow ^↑ and ^↓ to work also during "search filtering"

### ISSUE THREAD

**Issue by paletochen** [Canop/safecloset#32]
Let's say I have a huge list of secrets, to the point that ^↑ and ^↓ is not feasible.
I would still like to sort some secrets together.
It would be great if when i use the search feature to find relevant secrets through pattern search, that when i use ^↑ and ^↓ the entries are placed together.

Example: Interested secrets are in lines 1,2,3,4 and 1235
- When i search i manage to filter just those lines
- Go to the last entry (line 1235)
- Press ^↑
- Line 1235 will become Line 5

**Comment by paletochen** [comment]
@Canop I just tried it and, it is not doing what I was expecting.


Let's say I have the following drawer:

![1](https://github.com/Canop/safecloset/assets/109062850/a0e4660f-f487-4d3e-8c6d-e705b4f101c3)

I'd like to put all the **red - XX**  entries together

I try a 1st search filtering like this
![2](https://github.com/Canop/safecloset/assets/109062850/6e492b13-89f3-4c51-9e5b-307e64bed2c2)

I then move **red - 4** and bring it below **red - 3**
![3](https://github.com/Canop/safecloset/assets/109062850/520e7a76-50d1-4182-a327-87d00ed688fb)

When i remove the filtering, this is how it looks like
![4](https://github.com/Canop/safecloset/assets/109062850/849335b6-a97b-4d1c-8f70-e4583d9418d4)

If i try with a narrower filtering like this
![5](https://github.com/Canop/safecloset/assets/109062850/440af97b-ae77-4504-82d3-b23e3b22cbe9)

and then move **red - 4** again below **red - 3**
![6](https://github.com/Canop/safecloset/assets/109062850/4c0db566-fbaa-4a4d-89a1-f374a399328d)

it looks like this
![7](https://github.com/Canop/safecloset/assets/109062850/7bc386f5-1c68-4167-89f7-4afc7bd3fd9d)

If i try another approach, like bringing **red - 4** above **red -3**, to see if that does the trick
![8](https://github.com/Canop/safecloset/assets/109062850/99fe8432-9ab5-490a-8a1d-32e2179447c3)

**red -3** ends up being placed below all the entries that i had filtered out
![9](https://github.com/Canop/safecloset/assets/109062850/77ff29df-dcc5-4728-9d15-ec2e871c3866)



I am not sure that behavior would be expected and therefore look like a good feature.

The problem i have in my real drawer is that all those other entries in between the ones i want to bring together are counted in the hundreds, so the result of the sorting doesn't really help. The desired entries end up being too far apart

**Comment by Canop** [comment]
I don't see how moving is supposed to guess whether red-4 is supposed to go before or after pink-1 and pink-2. This doesn't really look like a move-when-filtering problem.
Isn't your real issue solved with https://github.com/Canop/safecloset/pull/35 ?

**Comment by paletochen** [comment]
> I don't see how moving is supposed to guess whether red-4 is supposed to go before or after pink-1 and pink-2. This doesn't really look like a move-when-filtering problem. Isn't your real issue solved with #35 ?

I just tried https://github.com/Canop/safecloset/pull/35 and I really like group matching. It gets closer to what i needed.

It would match exactly the expected behavior if i could also use https://github.com/Canop/safecloset/pull/33/ during a filtered search

I can imagine i would do, for the example mentioned above the following

Filter by **red -**
![5](https://github.com/Canop/safecloset/assets/109062850/f9678871-06f4-40a8-a3b0-b790290a5ca6)

Select from the menu: **Group matching**

Within the same filtered search, select from the menu: **Sort**

Would then be possible to have **Sort** available during a filtered search?

**Comment by Canop** [comment]
> Would then be possible to have Sort available during a filtered search?

I'll see. But if I do it, I'll do it with the minimal amount of moves, so it wouldn't group items, just change the filtered subset order.
