### ISSUE TITLE
Feature request: Let the user customize some common parameters and probably save to a config file

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [Canop/safecloset#4]
Right now some behaviors are hardcoded in SafeCloset. For example, the user must provide a pretty strong drawer password. If yo u left SafeCloset for a period of time it will automatically close itself. I think if behaviors like these could be customized by the user will make it more useful. You may say enforce a strong password and quickly close a closet are SafeCloset's security features. But there are some cases that the user may want a short password (easier to type) and want it keep open for a longer time. For example, if the information in a drawer is not that sensitive, but the user does want to protect it to some level, he can use SafeCloset with a short password. 

My suggestion is, if the user run safecloset without a configuration file (which is the default), safecloset will run with its default behavior. If the user create a `safecloset.config` file and put some customization parameter in it, safecloset will use the parameters there.

**Comment by Canop** [comment]
I'll probably just lower the minimal password length to 2 characters. You can't accidentally type a short password and if you use SafeCloset you're adult enough.

I'm reluctant to make it possible to remove the delay before closing because it would be a little too easy for somebody going near your computer to just add this setting.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
2 characters of length would be enough. 

Yes, it's reasonable. How long is current delay?

**Comment by Canop** [comment]
The current delay is 60 seconds: https://github.com/Canop/safecloset/blob/main/src/tui/mod.rs#L64
