### ISSUE TITLE
Question mark doesn't work

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [Canop/safecloset#7]
I'm using v0.2.5 and when safecloset starts, the `?` shortcut has never worked. Below is the log. I started safecloset, pressed `?` three times and `ctrl+x` exited. It seems safecloset did receive the key.

```
08:38:15.620 [INFO] cli_log::init: Starting safecloset v0.2.5 with log level DEBUG
08:38:15.621 [INFO] safecloset::cli: args: Args {
    version: false,
    hide: false,
    open: false,
    path: Some(
        "test",
    ),
}
08:38:15.888 [DEBUG] safecloset::tui::app: user event: Ok(Resize(107, 29))
08:38:20.380 [DEBUG] safecloset::tui::app: user event: Ok(Key(KeyEvent { code: Char('?'), modifiers: SHIFT }))
08:38:20.747 [DEBUG] safecloset::tui::app: user event: Ok(Key(KeyEvent { code: Char('?'), modifiers: SHIFT }))
08:38:21.077 [DEBUG] safecloset::tui::app: user event: Ok(Key(KeyEvent { code: Char('?'), modifiers: SHIFT }))
08:38:23.290 [DEBUG] safecloset::tui::app: user event: Ok(Key(KeyEvent { code: Char('x'), modifiers: CONTROL }))
08:38:23.290 [DEBUG] safecloset::tui::app_state: user requests save and quit
08:38:23.290 [DEBUG] safecloset::tui::app_state: self.close_drawer_input(false) took 300ns
08:38:23.290 [DEBUG] safecloset::tui::app: user requests quit
08:38:23.290 [INFO] safecloset: bye
```
Also as you can see in the following screen snapshot, there are duplicate help information at the bottom when I started safecloset. 
![image](https://user-images.githubusercontent.com/39968/136302912-95bc5c13-9232-40e8-9fb4-af115e72847f.png)
The length of the first help line is not equal to the second line, which is a little weird. For example, when I copy a cell, it looks like this.
![image](https://user-images.githubusercontent.com/39968/136303122-c0c17e78-6b78-49f1-8e4c-a36bae763ef3.png)

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Yes, the `?` can trigger help information now! Thanks for the improvement. The "resizing" problem still exists.

**Comment by Canop** [comment]
The resizing problem is totally unrelated. I remember I had the same problem at the beginning of broot for Windows users, I'll search my archives.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Oh, I just noticed you are the author of broot! I'm new in the Rust community, but I've tried broot in the past.
