### ISSUE TITLE
Question: Is it possible to always show the full cell content?

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [Canop/safecloset#8]
When the cell has multiple line, it collapsed by default and only show full content when the cell is active. Is it possible to always show the full cell content? That way, you can see the whole content at a glance, which is more useful imo.

**Comment by Canop** [comment]
(the reason I tagged this "undecided" is because a drawer should grow to many entries IMO - I'll probably come back to decide in a few weeks or months but other opinions are welcome)

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Do you think adding a shortcut to open/collapse all entries a good idea?

**Comment by Canop** [comment]
I'll probably do that.
